# Generated by Django 5.1.4 on 2026-05-03 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("radars", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pmid", models.CharField(max_length=20, unique=True)),
                ("title", models.TextField()),
                ("authors_json", models.JSONField(default=list)),
                ("journal", models.CharField(max_length=500)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("abstract", models.TextField(blank=True)),
                ("publication_date", models.DateField()),
                ("article_type", models.CharField(blank=True, max_length=255)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="AISummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("one_line_summary", models.TextField()),
                ("key_findings_json", models.JSONField(default=list)),
                (
                    "dataset_used",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "model_architecture",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "sample_size",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reported_metrics",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("relevance_score", models.IntegerField()),
                (
                    "novelty_tag",
                    models.CharField(
                        choices=[
                            ("incremental", "Incremental"),
                            ("new_approach", "New Approach"),
                            ("review", "Review"),
                            ("benchmark", "Benchmark"),
                            ("dataset", "Dataset"),
                            ("meta_analysis", "Meta-Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_used", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aisummary",
                        to="papers.paper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperRadar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_radars",
                        to="papers.paper",
                    ),
                ),
                (
                    "radar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_radars",
                        to="radars.radar",
                    ),
                ),
            ],
            options={
                "unique_together": {("paper", "radar")},
            },
        ),
        migrations.CreateModel(
            name="UserPaperAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("custom_tags_json", models.JSONField(default=list)),
                ("notes_text", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_actions",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "paper")},
            },
        ),
    ]
