# Generated by Django 5.1.4 on 2026-05-03 14:34

import apps.radars.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Radar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "pubmed_query",
                    models.TextField(
                        validators=[apps.radars.models.validate_pubmed_query]
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "filters_json",
                    models.JSONField(
                        default=dict,
                        help_text='Optional fetch filters. Expected shape: {"journal_whitelist": ["Nature", "NEJM"], "article_types": ["Clinical Trial", "Review"], "date_range_days": 30}',
                    ),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
